service: svelte-project
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
functions:
  - ${file(./backend/index/routes.yml)}
  - static: ${file(./backend/static/routes.yml)}
  - login: ${file(./backend/login/routes.yml)}

custom:
  serverless-offline:
    functionCleanupIdleTimeSeconds: 1
