service: svelte-project
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-offline
functions:
  - ${file(./services/index/routes.yml)}

custom:
  serverless-offline:
    functionCleanupIdleTimeSeconds: 1
