locales:
  handler: backend/index/handler.locales
  events:
    - httpApi:
        path: /locales/{locale}/{namespace}.json
        method: get

language:
  handler: backend/index/handler.language
  events:
    - httpApi:
        path: /language/{locale}
        method: get

post:
  handler: backend/index/handler.post
  events:
    - httpApi:
        path: /post
        method: post

table:
  handler: backend/index/handler.table
  events:
    - httpApi:
        path: /table
        method: get

api:
  handler: backend/index/handler.api
  events:
    - httpApi:
        path: /{path+}
        method: any
