static:
  handler: services.index.handler.static
  events:
    - httpApi: 
        path: /static/{path+}
        method: get

language:
  handler: services.index.handler.language
  events:
    - httpApi: 
        path: /language/{page}/{lang}.json
        method: get

login:
  handler: services.index.handler.login
  events:
    - httpApi: 
        path: /login
        method: post

api:
  handler: services.index.handler.api
  events:
    - httpApi:
        path: /{path+}
        method: any
