static:
  handler: api.index.handler.static
  events:
    - httpApi: 
        path: /static/{path+}
        method: get

login:
  handler: api.index.handler.login
  events:
    - httpApi: 
        path: /login
        method: post

api:
  handler: api.index.handler.api
  events:
    - httpApi:
        path: /{path+}
        method: any
